name = "mineard-api"
main = "src/index.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = false

[[d1_databases]]
binding = "DB"
database_name = "mineard"
database_id = "c77f74d5-39de-40d7-95a9-2ea035265231"

[triggers]
crons = ["50 * * * *", "0 4-14 * * *", "0 0 26 * *", "*/10 * * * *"]

[vars]
APP_ENV = "production"
FRONTEND_URL = "https://mineard-web.pages.dev"
MINEO_APP_ID = "jp.mineo.app"
MINEO_BASE_URL = "https://api.eonet.jp/mineo/v1"
MINEO_OIDC_TOKEN_URL = "https://login.eonet.jp/oidc/v1/token"
# MINEO_APP_VERSION and MINEO_OIDC_CLIENT_ID are managed as wrangler secrets
